// The source archive carries no macOS extended attributes.
//
// Every file a Mac has touched carries `com.apple.provenance`, and tar records
// it as a pax header — `SCHILY.xattr.com.apple.provenance` — beside the entry.
// `tar -t` does not show pax headers, so an archive reproduced byte-for-byte
// and listed entry-by-entry looked clean while carrying them; an extractor
// that cannot store the attribute writes a `._name` AppleDouble sidecar
// instead, and `._001_init.sql` was sent to Postgres as a query 321 times.
// The upload is inspected here as bytes, which is the only view that shows it.

import { spawn, spawnSync } from "node:child_process";
import { createServer, type Server } from "node:http";
import { gunzipSync } from "node:zlib";
import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, describe, expect, it } from "vitest";

describe("deploy.mjs uploads an archive without extended attributes", () => {
  let api: Server | undefined;
  afterEach(() => api?.close());

  function fakePlatform(): Promise<{ port: number; seen: { put?: Buffer } }> {
    const seen: { put?: Buffer } = {};
    api = createServer((req, res) => {
      const chunks: Buffer[] = [];
      req.on("data", (c: Buffer) => chunks.push(c));
      req.on("end", () => {
        const body = Buffer.concat(chunks);
        const json = (status: number, payload: unknown) => {
          res.writeHead(status, { "content-type": "application/json" });
          res.end(JSON.stringify(payload));
        };
        const port = (api!.address() as { port: number }).port;
        if (req.method === "POST" && req.url === "/api/deploy") return json(200, { deploymentId: "d1", uploadUrl: `http://127.0.0.1:${port}/upload` });
        if (req.method === "PUT" && req.url === "/upload") { seen.put = body; res.writeHead(200); return res.end(); }
        if (req.method === "POST" && req.url === "/api/deployments/d1/start") return json(200, {});
        if (req.method === "GET" && req.url === "/api/deployments/d1") return json(200, { status: "failed", errorCode: "build_failed", error: "fake platform stops here" });
        json(404, { error: "unexpected request" });
      });
    });
    return new Promise((resolve) => api!.listen(0, "127.0.0.1", () => resolve({ port: (api!.address() as { port: number }).port, seen })));
  }

  /** A repo whose tracked file carries an extended attribute, where the OS allows one to be set. */
  function repo(): { dir: string; attributed: boolean } {
    const dir = mkdtempSync(join(tmpdir(), "tamari-xattr-"));
    writeFileSync(join(dir, "tamari.json"), JSON.stringify({ app: "x", name: "X", runtime: "node", resourceClass: "personal", healthPath: "/healthz", requiresDatabase: true }));
    mkdirSync(join(dir, "migrations"));
    const sql = join(dir, "migrations/001_init.sql");
    writeFileSync(sql, "CREATE TABLE t (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY);\n");
    const set = process.platform === "darwin"
      ? spawnSync("xattr", ["-w", "com.apple.provenance", "1", sql])
      : spawnSync("setfattr", ["-n", "user.com.apple.provenance", "-v", "1", sql]);
    spawnSync("git", ["init", "-q"], { cwd: dir });
    spawnSync("git", ["add", "-A"], { cwd: dir });
    return { dir, attributed: set.status === 0 };
  }

  function run(dir: string, port: number): Promise<{ out: { errorCode: string }; stderr: string }> {
    return new Promise((resolve, reject) => {
      const child = spawn(process.execPath, [join(process.cwd(), "skills/tamari/deploy.mjs")], {
        cwd: dir,
        env: { ...process.env, TAMARI_API: `http://127.0.0.1:${port}`, TAMARI_TOKEN: "t" },
      });
      let stdout = "";
      let stderr = "";
      child.stdout.on("data", (c: Buffer) => (stdout += c.toString("utf8")));
      child.stderr.on("data", (c: Buffer) => (stderr += c.toString("utf8")));
      const timer = setTimeout(() => child.kill("SIGTERM"), 20_000);
      child.on("close", () => {
        clearTimeout(timer);
        try { resolve({ out: JSON.parse(stdout), stderr }); } catch { reject(new Error(`no JSON on stdout; stderr:\n${stderr}`)); }
      });
    });
  }

  it("carries no xattr pax records and no AppleDouble entries, even for an attributed file", async () => {
    const { port, seen } = await fakePlatform();
    const { dir, attributed } = repo();

    const { out, stderr } = await run(dir, port);

    expect(out.errorCode).toBe("build_failed"); // the upload happened
    expect(seen.put).toBeDefined();
    const tar = gunzipSync(seen.put!).toString("latin1");
    expect(tar).toContain("migrations/001_init.sql");
    expect(tar).not.toMatch(/SCHILY\.xattr|LIBARCHIVE\.xattr/);
    expect(tar).not.toContain("._001_init.sql");
    expect(tar).not.toContain("Mac OS X");
    // No fallback note: this tar knew the flag.
    expect(stderr).not.toMatch(/does not support --no-xattrs/);
    // On a platform where the attribute could not be set this proves less; say so in the output.
    if (!attributed) console.log("note: extended attribute could not be set here; the archive was clean regardless");
  });
});
